### ISSUE TITLE
Todoist throwing on array access

### ISSUE THREAD

**Issue by bright-star** [hanneskaeufler/danger-todoist#36]
### Log

```
$ bundle exec danger

[!] The exception involves the following plugins:
 -  danger-todoist

bundler: failed to load command: danger (/home/ubuntu/repo/vendor/bundle/ruby/2.2.0/bin/danger)
Danger::DSLError: 
[!] Invalid `Dangerfile` file: undefined method `[]' for nil:NilClass
 #  from Dangerfile:29
 #  -------------------------------------------
 #  # Warn if TODOs are present in code
 >  todoist.warn_for_todos
 #  todoist.print_todos_table
 #  -------------------------------------------

  /home/ubuntu/repo/vendor/bundle/ruby/2.2.0/gems/git-1.3.0/lib/git/diff.rb:64:in `[]'
  /home/ubuntu/repo/vendor/bundle/ruby/2.2.0/gems/danger-4.1.1/lib/danger/danger_core/plugins/dangerfile_git_plugin.rb:115:in `diff_for_file'
  /home/ubuntu/repo/vendor/bundle/ruby/2.2.0/gems/danger-todoist-1.2.1/lib/todoist/plugin.rb:133:in `block in diffs_of_interest'
  /home/ubuntu/repo/vendor/bundle/ruby/2.2.0/gems/danger-todoist-1.2.1/lib/todoist/plugin.rb:133:in `map'
  /home/ubuntu/repo/vendor/bundle/ruby/2.2.0/gems/danger-todoist-1.2.1/lib/todoist/plugin.rb:133:in `diffs_of_interest'
  /home/ubuntu/repo/vendor/bundle/ruby/2.2.0/gems/danger-todoist-1.2.1/lib/todoist/plugin.rb:112:in `find_todos'
  /home/ubuntu/repo/vendor/bundle/ruby/2.2.0/gems/danger-todoist-1.2.1/lib/todoist/plugin.rb:103:in `call_method_for_todos'
  /home/ubuntu/repo/vendor/bundle/ruby/2.2.0/gems/danger-todoist-1.2.1/lib/todoist/plugin.rb:55:in `warn_for_todos'
  Dangerfile:29:in `block in parse'
  /home/ubuntu/repo/vendor/bundle/ruby/2.2.0/gems/danger-4.1.1/lib/danger/danger_core/dangerfile.rb:199:in `eval'
  /home/ubuntu/repo/vendor/bundle/ruby/2.2.0/gems/danger-4.1.1/lib/danger/danger_core/dangerfile.rb:199:in `block in parse'
  /home/ubuntu/repo/vendor/bundle/ruby/2.2.0/gems/danger-4.1.1/lib/danger/danger_core/dangerfile.rb:195:in `instance_eval'
  /home/ubuntu/repo/vendor/bundle/ruby/2.2.0/gems/danger-4.1.1/lib/danger/danger_core/dangerfile.rb:195:in `parse'
  /home/ubuntu/repo/vendor/bundle/ruby/2.2.0/gems/danger-4.1.1/lib/danger/danger_core/dangerfile.rb:272:in `run'
  /home/ubuntu/repo/vendor/bundle/ruby/2.2.0/gems/danger-4.1.1/lib/danger/danger_core/executor.rb:27:in `run'
  /home/ubuntu/repo/vendor/bundle/ruby/2.2.0/gems/danger-4.1.1/lib/danger/commands/runner.rb:66:in `run'
  /home/ubuntu/repo/vendor/bundle/ruby/2.2.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
  /home/ubuntu/repo/vendor/bundle/ruby/2.2.0/gems/danger-4.1.1/bin/danger:5:in `<top (required)>'
  /home/ubuntu/repo/vendor/bundle/ruby/2.2.0/bin/danger:23:in `load'
  /home/ubuntu/repo/vendor/bundle/ruby/2.2.0/bin/danger:23:in `<top (required)>'

bundle exec danger returned exit code 1
```

### Gemfile

```ruby
# frozen_string_literal: true
source "https://rubygems.org"

gem 'danger', '4.1.1'
gem 'danger-todoist', '1.2.1' # Checks for TODO etc in commits
gem 'danger-commit_lint' # Lints commit messages
gem 'danger-mention' # Mention potential reviewers
```

**Comment by hanneskaeufler** [comment]
Hey mate, thanks again for reporting. I went another route to get to the root of this issue this time, if you ever see something like
```
* danger-todoist was unable to determine diff for "???\".
```
please let me know. This is added as markdown to your danger comment, so will not affect build status.

**I'd love for you to check out v1.2.2 of danger-todoist.**

**Comment by bright-star** [comment]
Thanks, I'll test it this week! Much appreciated.
